# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Society of Network Scientists
tagline:          "A Network Science Student Organization at UW"
description:      "We're a student run organization at University of Washington aimed at encouraging Network Science research on campus."
url:              https://societynetworkscienceuw.github.io/

author:
  name:           'Kishore Vasan'
  url:            https://www.kishorevasan.me

paginate:         5

# Custom vars
# gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
