# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Machines Who Learn
tagline:          "A ML / AI / Data Science Student Organization at UW"
description:      "We're a ML / AI / Data Science student organization at the University of Washington."
url:              https://machineswholearn.github.io/

author:
  name:           'Nelson Liu'
  url:            https://homes.cs.washington.edu/~nfliu/

paginate:         5

# Custom vars
# gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
