# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Society of Network Scientists
tagline:          'University of Washington'
description:      'A student run organization focussed on encouraging Network Science research at the University of Washington.'
url:              http://societynetworkscienceuw.github.io
baseurl:          /

author:
  name:           'Kishore Vasan'
  url:            https://www.kishorevasan.me

paginate:         5


github:
  repo:           https://github.com/societynetworkscienceuw/societynetworkscienceuw.github.io
